language: scala

scala:
  - 2.11.8

sudo: false
services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)